name: praca_inzynierska_front
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:   # <-- przeniesione na ten poziom
    sdk: flutter
  http: ^0.13.5
  http_parser: ^4.1.2
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  intl: ^0.19.0
  flutter_tex: ^4.0.9  # Alternative LaTeX rendering

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
